services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
      POSTGRES_DB: ${POSTGRES_DB:-landingdb}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./apps/backend
    depends_on:
      - db
    environment:
      APP_NAME: ${APP_NAME:-landing-backend}
      LOG_LEVEL: ${LOG_LEVEL:-debug}
      DATABASE_URL: postgresql://app:app@db:5432/landingdb?schema=public
      PORT: 4000
      NODE_ENV: development
      JWT_SECRET: ${JWT_SECRET:-dev-secret}
      JWT_ACCESS_MINUTES: ${JWT_ACCESS_MINUTES:-15}
      JWT_REFRESH_DAYS: ${JWT_REFRESH_DAYS:-30}
      MAGIC_LINK_MINUTES: ${MAGIC_LINK_MINUTES:-15}
      INVITE_DAYS: ${INVITE_DAYS:-7}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-}
    ports:
      - "4000:4000"
    volumes:
      - ./apps/backend:/app
      - /app/node_modules

  frontend:
    build: ./apps/frontend
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules

volumes:
  db_data:
